1.4.0 (2017-09-15)
==================

* Метод ``CloudPayments.create_receipt`` теперь возвращает уникальный идентификатор чека, поставленного в очередь. 


1.3.2 (2017-08-30)
==================

* В метод ``CloudPayments.confirm_payment`` добавлен необязательный аргумент ``data`` для передачи в запросе произвольных данных.


1.3.1 (2017-06-10)
==================

* Исправлена ошибка при установке на Python 3.


1.3 (2017-06-10)
================

* Добавлен метод ``CloudPayments.create_receipt`` для формирования кассового чека.
* В метод ``CloudPayments.test`` добавлен необязательный аргумент ``request_id`` для передачи идентификатора идемпотентного запроса.
* Метод ``CloudPayments.test`` теперь возвращает сообщение, полученное от сервера.
* Тип исключения, бросаемого методом ``CloudPayments.finish_3d_secure_authentication``, изменен с ``CloudPaymentsError`` на ``PaymentError``.
* В исключение ``PaymentError`` добавлены поля ``verbose_reason`` и ``verbose_message``, содержащие описания ошибок из документации.


1.2 (2016-06-21)
================

* Исправлено неверное форматирование дат, из-за которого сервис неправильно интерпретировал передаваемые даты.
* В исключение ``PaymentError`` добавлено поле cardholder_message с сообщением, которое выводится для пользователя.
* Метод ``redirect_url`` у ``Secure3d`` заменен на ``redirect_params``, возвращающий словарь с параметрами для POST-запроса.


1.1 (2016-06-03)
================

* Исправлены ошибки, возникающие, когда при оплате по криптограмме требуется 3-D Secure аутентификация.